# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Guzel Ishmaeva
first_name: Guzel
middle_name:
last_name: Ishmaeva
contact_note: >
description: >
  Personal academic website.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
keywords:
lang: en
icon:

url: https://guzelishmaeva.github.io
baseurl:
last_updated: false
back_to_top: true

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

repo_theme_light: default
repo_theme_dark: dark

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true
search_enabled: true
socials_in_search: false
posts_in_search: false
bib_search: false

max_width: 930px

# -----------------------------------------------------------------------------
# Open Graph & Schema.org
# -----------------------------------------------------------------------------

serve_og_meta: false
serve_schema_org: false
og_image:

# -----------------------------------------------------------------------------
# Analytics (disabled)
# -----------------------------------------------------------------------------

google_analytics:
cronitor_analytics:
pirsch_analytics:
openpanel_analytics:
google_site_verification:
bing_site_verification:

# -----------------------------------------------------------------------------
# Blog (disabled)
# -----------------------------------------------------------------------------

blog_name: ""
blog_description: ""
permalink: /blog/:year/:title/
lsi: false

pagination:
  enabled: false

related_blog_posts:
  enabled: false

# -----------------------------------------------------------------------------
# Newsletter (disabled)
# -----------------------------------------------------------------------------

newsletter:
  enabled: false

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  projects:
    output: true

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

include: ["_pages"]
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - vendor

keep_files:
  - CNAME
  - .nojekyll

# -----------------------------------------------------------------------------
# Plug-ins (only GitHub Pages–supported)
# -----------------------------------------------------------------------------

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

# -----------------------------------------------------------------------------
# Sass
# -----------------------------------------------------------------------------

sass:
  style: compressed

